- groups.rst
- summary.yaml
This PR adds Karlo Mrakovcic to the University of Washington contributing group.
Rendered version can be previewed [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-update-uw/index.html).
> Update University of Washington group

- groups.rst
- summary.yaml
This PR adds the UC-Davis group.
Rendered version can be previewed [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-update-uc-davis/index.html).
> Add UC-Davis group

- groups.rst
- summary.yaml
This PR adds Rob Knop to the contributor list for US/Chile-11.
Rendered version [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-update-US-Chile-11/index.html).
> Update US/Chile-11 Group

- summary.yaml
This PR makes an adjustment to #12 to add Audrey Budlong to summary.yaml file that is used as source of truth when compiling the document.
> Add Audrey Budlong to UW group

- generate_summary.py
- groups.rst
- index.rst
- summary.yaml
This PR adds the photometric redshift team as an ex officio contribution.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-photoz/index.html).
See [A Roadmap to Photometric Redshifts for the LSST Object Catalog ](https://dmtn-049.lsst.io/) for further context.
> Add photometric redshift team

- groups.rst
- summary.yaml
This PR adds Benjamin Levine and Prakruth Adari to US/Chile-16.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-blevine/index.html).
> Add Benjamin Levine and Prakruth Adari to US/Chile-16

- groups.rst
- summary.yaml
This PR adds Xiangchong Li to US/Chile-04.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-xli/index.html).
> Add Xiangchong Li to US/Chile-04

- groups.rst
- requirements.txt
- summary.yaml
This PR adds Philippe Gris to FRA-INP-S8.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-pgris/index.html).
> Add Philippe Gris to FRA-INP-S8

- groups.rst
- summary.yaml
This PR adds Bekah Polen and Michael Troxel to Duke University.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-duke/index.html).
> Add Bekah Polen and Michael Troxel to Duke University

- groups.rst
- summary.yaml
This PR adds Anthony Englert and Jiaxuan Li to US/Chile-12.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-aenglert/index.html).
> Add Anthony Englert and Jiaxuan Li to US/Chile-12

- groups.rst
- summary.yaml
This PR adds Alexandra Amon and Chihway Chang to US/Chile-04.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-aamon_cchang/index.html).
> Add Alexandra Amon and Chihway Chang to US/Chile-04

- groups.rst
- summary.yaml
This PR adds Laura Toribio to ESP-BCM-S2.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-ltoribio/index.html).
> Add Laura Toribio to ESP-BCM-S2

- groups.rst
- summary.yaml
This PR adds Andrea Jeremie to FRA-INP-S8.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-ajeremie/index.html).
> Add Andrea Jeremie to FRA-INP-S8

- groups.rst
- summary.yaml
This PR adds Andy Park to US/Chile-04 and US/Chile-05.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-apark/index.html).
> Add Andy Park to US/Chile-04 and US/Chile-05

- groups.rst
- summary.yaml
This PR adds Nathan Amouroux to FRA-INP-S8.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-namouroux/index.html).
> Add Nathan Amouroux to FRA-INP-S8

- groups.rst
- summary.yaml
This PR adds Behnood Bandi to UKD-UKD-S13.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-bbandi/index.html).
> Add Behnood Bandi to UKD-UKD-S13

- groups.rst
- summary.yaml
This PR adds Larom Segev to Harvard.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-lsegev/index.html).
> Add Larom Segev to Harvard

- groups.rst
- summary.yaml
This PR adds Easton Honaker to US/Chile-08.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-ehonaker/index.html).
> Add Easton Honaker to US/Chile-08

- groups.rst
- summary.yaml
This PR adds Ricardo Sanchez to ITA-INA-S22.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-rsanchez/index.html).
> Add Ricardo Sanchez to ITA-INA-S22

- groups.rst
- summary.yaml
This PR adds Kelian Sommer to FRA-INP-S8.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-ksommer/index.html).
> Add Kelian Sommer to FRA-INP-S8

- groups.rst
- summary.yaml
This PR adds Michelle Lin to Harvard.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-mlin/index.html).
> Add Michelle Lin to Harvard

- groups.rst
- summary.yaml
This PR adds Doug Yang to Harvard.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-dyang/index.html).
> Add Doug Yang to Harvard

- groups.rst
- summary.yaml
This PR adds Jazmine Jefferson and Yuuki Omori to US/Chile-04.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-jJefferson_yomori/index.html).
> Add Jazmine Jefferson and Yuuki Omori to US/Chile-04

- groups.rst
- summary.yaml
This PR adds Corentin Ravoux and Yassine Faris to FRA-INP-S8.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-cravoux_yfaris/index.html).
> Add Corentin Ravoux and Yassine Faris to FRA-INP-S8

- groups.rst
- summary.yaml
This PR adds Robert Hynes to US/Chile-11.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-rhynes/index.html).
> Add Robert Hynes to US/Chile-11

- generate_summary.py
- groups.rst
- summary.yaml
add the three newest pz team members
> Add three members to Photometric Redshift Team

- groups.rst
- summary.yaml
This PR adds Masao Sako and grad students Aditya Inada Somasundaram, Jillian Paulin, and Cole Meldorf to US/Chile-11.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-msako/index.html).
> Add Masao Sako group to US/Chile-11

- groups.rst
- summary.yaml
This PR adds Cyrille Rosset to FRA-INP-S8.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-crosset/index.html).
> Add Cyrille Rosset to FRA-INP-S8

- groups.rst
- summary.yaml
This PR adds Kane Sjoberg and Meghan Marangola to Harvard.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-ksjoberg/index.html).
> Add Kane Sjoberg and Meghan Marangola to Harvard

- groups.rst
- summary.yaml
This PR adds Manon Ramel to FRA-INP-S9.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-mramel/index.html).
> Add Manon Ramel to FRA-INP-S9

- groups.rst
- summary.yaml
This PR adds Xiangyu Huang to US/Chile-09.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-xhuang/index.html).
> Add Xiangyu Huang to US/Chile-09

- groups.rst
- summary.yaml
This PR adds Martin Millon to US/Chile-11.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-mmillon/index.html).
> Add Martin Millon to US/Chile-11

- groups.rst
- summary.yaml
This PR adds Poshak Gandhi to UKD-UKD-S13.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-pgandhi/index.html).
> Add Poshak Gandhi to UKD-UKD-S13

- groups.rst
- summary.yaml
This PR adds Thierry Souverin to FRA-INP-S6.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-tsouverin/index.html).
> Add Thierry Souverin to FRA-INP-S6

- groups.rst
- summary.yaml
This PR adds Conghao Zhou to US/Chile-12.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-czhou/index.html).
> Add Conghao Zhou to US/Chile-12

- groups.rst
- summary.yaml
This PR adds Tae-Hyeon Shin to US/Chile-05.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-tshin/index.html).
> Add Tae-Hyeon Shin to US/Chile-05

- groups.rst
- summary.yaml
This PR adds Kayleigh Excell to UW-Madison.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-kexcell/index.html).
> Add Kayleigh Excell to UW-Madison

- groups.rst
- summary.yaml
This PR adds Enya Van den Abeele to FRA-INP-S6 and FRA-INP-S7.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-van_den_abeele/index.html).
> Add Enya Van den Abeele to FRA-INP-S6 and FRA-INP-S7

- groups.rst
- summary.yaml
This PR adds Soren Helhoski to US/Chile-12.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-shelhoski/index.html).
> Add Soren Helhoski to US/Chile-12

- groups.rst
- summary.yaml
This PR adds Luca Rosignoli to ITA-INA-S21.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-lrosignoli/index.html).
> Add Luca Rosignoli to ITA-INA-S21

- groups.rst
- summary.yaml
This PR 
- Adds Didier Verkindt and Antoine Bernard to FRA-INP-S8
- Adds Anavi Uppal to US/Chile-06
- Adds Elham Saremi, Richard McMahon, Manda Banerji, Sugata Kaviraj, Chris Collins to UKD-UKD-S13
- Adds Katherine Laliotis to US/Chile-04
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-11oct2024/index.html).
> Update multiple contributions 11 October 2024

- groups.rst
- summary.yaml
This PR adds Alessio Taranto to ITA-INA-S21.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-ataranto/index.html).
> Add Alessio Taranto to ITA-INA-S21

- groups.rst
- summary.yaml
This PR adds
* Eduardo Barroso to FRA-INP-S8
* Anupreeta More to UKD-UKD-S13
* Meagan Porter to US/Chile-14
* Norris Bach to UC-Davis
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-dec_2024/index.html).
> Add multiple contributions December 2024

- groups.rst
- summary.yaml
This PR adds Julian Beas-Gonzalez to UW-Madison.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-jbeas-gonzalez/index.html).
> Add Julian Beas-Gonzalez to UW-Madison

- groups.rst
- summary.yaml
This PR adds several commissioners.
FRA-INP-S6:
- Nathan Amouroux
- Johan Bregeon
FRA-INP-S8:
- Narei Lorenzo-Martinez
- Vincent Reverdy
- Tania Regimbau
- Yves Zolnierowski
- Marina Masson
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-fra-inp_dec_2024/index.html).
> Update FRA-INP for Dec 2024

- groups.rst
- summary.yaml
This PR adds Jaemyoung (Jason) Lee to US/Chile-11.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-bechtol-jlee/index.html).
> Add Jaemyoung (Jason) Lee to US/Chile-11

- groups.rst
- summary.yaml
This PR adds 
- Aprajita Verma
- Kathy Romer
- Paul Giles
- Andres Ponte Perez
- Suhail Dhawan
to UKD-UKD-S13 and
- Timo Anguita
to US/Chile-09.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-ukd-ukd-s13_update_mar_2025/index.html).
> Update UKD-UKD-S13 and US/Chile-09

- groups.rst
- summary.yaml
This PR adds 
FRA-INP-S6
- IJCLab (J. Neveu) : Angelo Lamure-Fontani
FRA-INP-S8
- LPSC (J. Bregeon) : Dimitri Buffat
- LAPP (V. Reverdy) : Laurent Magri-Stella
FRA-INP-S9
- APC (M. Ricci) : Eva Vuilloz
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-update_fra-inp-s6-s8-s9/index.html).
> Update FRA-INP-S6, S8 and S9

- groups.rst
- summary.yaml
This PR adds Reese Wilkinson to UKD-UKD-S13.
Live draft available [here](https://sitcomtn-050.lsst.io/v/u-kbechtol-rwilkinson/index.html).
> Add Reese Wilkinson to UKD-UKD-S13

- groups.rst
- summary.yaml
This PR adds Kevin Napier, Meg Schwamb, Devanshi Singh, and Ian Chow to support Solar System science validation studies.
> Updates for Solar System science validation
